%! Class = ppc-ufscar
%! Author = Jander Moreira (moreira.jander@gmail.com)
%! Date = 25/04/2025

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{ppc-ufscar}[2025-04-25 Classe para a edição de Projetos Pedagógicos de Curso]

\LoadClass[12pt]{report}
\RequirePackage[T1]{fontenc}
\RequirePackage[utf8]{inputenc}
\RequirePackage[brazilian]{babel}

%
% Pacotes
\RequirePackage{textcomp}
\RequirePackage{xcolor}
\RequirePackage{geometry}
\RequirePackage{setspace}
\RequirePackage[all]{nowidow}
\RequirePackage{array}


%
% Leiaute

\geometry{left = 2cm, right = 1.5cm, top = 1.5cm, bottom = 2cm}
\onehalfspacing
\sloppy



