%! Class = ppc-ufscar
%! Author = Jander Moreira (moreira.jander@gmail.com)
%! Date = 25/04/2025


\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{ppc-ufscar}[2025-04-25 Classe para a edição de Projetos Pedagógicos de Curso]
\LoadClass[12pt]{report}

\RequirePackage{geometry}
\RequirePackage{setspace}

%
% Leiaute
\geometry{left = 2cm, right = 1.5cm, top = 1.5cm, bottom = 2cm}
\onehalfspacing

\LoadPackage{ppc-ufscar}